name: Publish

on:
  push:
    branches: [ main ]

jobs:

  test:
  # ... (no changes)

  apk:
  # ... (no changes)

  firebase:
  # ... (no changes)

  distribute:
    name: Distribute app bundle to Play Store
    needs: [firebase, apk, test]
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Version bump
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.FRIENDS_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.FRIENDS_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Set up Google Play credentials
        run: echo "${{ secrets.GOOGLE_SERVICES_API }}" > $GITHUB_WORKSPACE/service_account.json

      - name: Deploy to internal
        run: |
          cp app/build/outputs/bundle/release/app-release.aab $GITHUB_WORKSPACE/app-release.aab
          cp $GITHUB_WORKSPACE/service_account.json $GITHUB_WORKSPACE/service_account.json
        continue-on-error: true

      - name: Upload to Play Store
        if: success()
        uses: r0adkll/upload-google-play@v1.0.0
        with:
          serviceAccountJson: $GITHUB_WORKSPACE/service_account.json
          packageName: com.cicd.friends
          releaseFile: $GITHUB_WORKSPACE/app-release.aab
          track: internal
          status: 'completed'
          whatsNewDirectory: whatsNewDirectory/
